### ISSUE TITLE
图片是生成了，但是是0kb,没有内容，啥问题？

### ISSUE THREAD

**Issue by actorTian** [Abbotton/ios-png-parser#1]
图片是生成了，但是是0kb,没有内容，啥问题？

**Comment by Abbotton** [comment]
感谢反馈:heart:, 已测试并更新Readme中相关内容.

**Comment by XuShall** [comment]
这个问题解决了吗? 我也遇到同样的问题,作者自己测试没问题吗?

**Comment by Abbotton** [comment]
上传一下IPA包.我测一下

**Comment by Abbotton** [comment]
> 这个问题解决了吗? 我也遇到同样的问题,作者自己测试没问题吗?

上传一下图片,我测一下.

**Comment by XuShall** [comment]
> > 这个问题解决了吗? 我也遇到同样的问题,作者自己测试没问题吗?
> 
> 上传一下图片,我测一下.
「AppIcon60x60@3x.png」，点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。
链接：https://www.aliyundrive.com/s/sbFzXP3W68E

**Comment by XuShall** [comment]
> > 这个问题解决了吗? 我也遇到同样的问题,作者自己测试没问题吗?
> 
> 上传一下图片,我测一下.

把图片拖入google浏览器,能访问,就应该算是好了.

**Comment by Abbotton** [comment]
![微信截图_20211213111708](https://user-images.githubusercontent.com/16308633/145747022-a6da6a81-d618-499f-ae4f-fd4c9076cb43.png)

.IPA文件文件解压后,文件夹中的应用图标图片用普通看图软件是打不开的.应该是全黑色的, 本扩展只解析那一类图片, 您现在发的这个图片只是在浏览器打不开,但用看图软件可以打开.方便的话可以把IPA文件拖拽至本页编辑器上传一下.

**Comment by XuShall** [comment]
> ![微信截图_20211213111708](https://user-images.githubusercontent.com/16308633/145747022-a6da6a81-d618-499f-ae4f-fd4c9076cb43.png)
> 
> .IPA文件文件解压后,文件夹中的应用图标图片用普通看图软件是打不开的.应该是全黑色的, 本扩展只解析那一类图片, 您现在发的这个图片只是在浏览器打不开,但用看图软件可以打开.方便的话可以把IPA文件拖拽至本页编辑器上传一下.
[game.zip](https://github.com/Abbotton/ios-png-parser/files/7700763/game.zip)

**Comment by Abbotton** [comment]
![decrypted](https://user-images.githubusercontent.com/16308633/145762272-3c78904f-5eb4-4d40-a4b8-a14265866767.png)
 您好,我本地测试并无问题,这是解码之后的图片. 请确认解码图片有可写入的权限.代码完全从README.md中拷贝的.

```php
require 'vendor/autoload.php';

use IosPngParser\Parser;

$parser = new Parser();
$encryptedPngFile = "./encrypted.png";
$decryptedPngFile = './decrypted.png';
$parser::fix($encryptedPngFile, $decryptedPngFile);
```

**Comment by XuShall** [comment]
> ![decrypted](https://user-images.githubusercontent.com/16308633/145762272-3c78904f-5eb4-4d40-a4b8-a14265866767.png) 您好,我本地测试并无问题,这是解码之后的图片. 请确认解码图片有可写入的权限.代码完全从README.md中拷贝的.
> 
> ```
> require 'vendor/autoload.php';
> 
> use IosPngParser\Parser;
> 
> $parser = new Parser();
> $encryptedPngFile = "./encrypted.png";
> $decryptedPngFile = './decrypted.png';
> $parser::fix($encryptedPngFile, $decryptedPngFile);
> ```

可以了 感谢!🙏
